### Текстовые файлы. Работа с файлами.
Прежде, чем работать с файлом, его надо открыть. С этим замечательно справится встроенная функция open:

Режим	|  Обозначение
:-------|:--------------
'r'	| открытие на чтение (является значением по умолчанию).
'w'	| открытие на запись, содержимое файла удаляется, если файла не существует, создается новый.
'x'	| открытие на запись, если файла не существует, иначе исключение.
'a'	| открытие на дозапись, информация добавляется в конец файла.
'b'	| открытие в двоичном режиме.
't'	| открытие в текстовом режиме (является значением по умолчанию).
'+'	| открытие на чтение и запись

In [1]:
f = open('files/text.txt', 'r')

### Чтение из файла
Первый - метод read, читающий весь файл целиком, если был вызван без аргументов, и n символов, если был вызван с аргументом (целым числом n).

In [2]:
f.read(1)

'H'

In [3]:
f.read()

'ello SM!!\n\nThe end.\n\n'

In [4]:
f.read()

''

In [5]:
f.close()

In [6]:
f = open('files/text.txt', 'r')
print(f.read()
     
     
     
     )

f.close()

Hello SM!!

The end.




In [7]:
with open('files/text.txt', 'r') as f:
    print(f.read())

Hello SM!!

The end.




In [8]:
with open('files/text.txt', 'r') as f:
    print(f.readlines()) 

['Hello SM!!\n', '\n', 'The end.\n', '\n']


In [9]:
with open('files/text.txt', 'r') as f:
    print('1', f.readline())
    print('2', f.readline())
    print('3', f.readline())
    print('4', f.readline())

1 Hello SM!!

2 

3 The end.

4 



In [10]:
with open('files/text.txt', 'r') as f:
    for line in f:
        print('###', line)

### Hello SM!!

### 

### The end.

### 



### Запись в файл
Теперь рассмотрим запись в файл. Попробуем записать в файл вот такой вот список:

In [11]:
lst = [str(i)+str(i-1) for i in range(13)]
lst

['0-1',
 '10',
 '21',
 '32',
 '43',
 '54',
 '65',
 '76',
 '87',
 '98',
 '109',
 '1110',
 '1211']

In [12]:
with open('files/text_w.txt', 'w') as f:
    f.write(lst)

TypeError: write() argument must be str, not list

In [13]:
with open('files/text_w.txt', 'w') as f:
    f.write(str(lst))

In [14]:
with open('files/text_w.txt', 'r') as f:
    lst_f = f.read()
lst_f

"['0-1', '10', '21', '32', '43', '54', '65', '76', '87', '98', '109', '1110', '1211']"

In [15]:
with open('files/text_w.txt', 'w') as f:
    for index in lst:
        f.write(index + '\n')
        
with open('files/text_w.txt', 'r') as f:
    lst_f = f.read()
lst_f

'0-1\n10\n21\n32\n43\n54\n65\n76\n87\n98\n109\n1110\n1211\n'

In [16]:
with open('files/text_w.txt', 'r') as f:
    lst2 = [line for line in f]
lst2

['0-1\n',
 '10\n',
 '21\n',
 '32\n',
 '43\n',
 '54\n',
 '65\n',
 '76\n',
 '87\n',
 '98\n',
 '109\n',
 '1110\n',
 '1211\n']

In [17]:
with open('files/text_w.txt', 'r') as f:
    lst2 = [line.strip() for line in f]
lst2

['0-1',
 '10',
 '21',
 '32',
 '43',
 '54',
 '65',
 '76',
 '87',
 '98',
 '109',
 '1110',
 '1211']

In [18]:
with open('files/text_w.txt', 'a') as f:
    for index in lst:
        f.write(index + '\n')
        
with open('files/text_w.txt', 'r') as f:
    lst_f = f.read()
lst_f

'0-1\n10\n21\n32\n43\n54\n65\n76\n87\n98\n109\n1110\n1211\n0-1\n10\n21\n32\n43\n54\n65\n76\n87\n98\n109\n1110\n1211\n'

In [19]:
with open('files/text_w.txt', 'r') as f:
    lst2 = [line.strip() for line in f]
lst2

['0-1',
 '10',
 '21',
 '32',
 '43',
 '54',
 '65',
 '76',
 '87',
 '98',
 '109',
 '1110',
 '1211',
 '0-1',
 '10',
 '21',
 '32',
 '43',
 '54',
 '65',
 '76',
 '87',
 '98',
 '109',
 '1110',
 '1211']

### CSV файлы

Одним из распространенных файловых форматов, которые хранят в удобном виде информацию, является формат **csv**. Каждая строка в файле csv представляет отдельную запись или строку, которая состоит из отдельных столбцов, разделенных запятыми. Собственно поэтому формат и называется Comma Separated Values. Но хотя формат csv - это формат текстовых файлов, Python для упрощения работы с ним предоставляет специальный встроенный модуль **csv**.

In [21]:
import csv

FILENAME = "files/users.csv"

users = [
    ["Tom", 28],
    ["Alice", 23],
    ["Bob", 34]
]

with open(FILENAME, "w", newline="") as file:
    writer = csv.writer(file, delimiter="|")
    writer.writerows(users)

In [22]:
with open(FILENAME, "a", newline="") as file:
    user = ["Sam", 31]
    writer = csv.writer(file, delimiter="|")
    writer.writerow(user)

In [23]:
with open(FILENAME, "r", newline="") as file:
    reader = csv.reader(file, delimiter="|")
    for row in reader:
        print(row[0], " - ", row[1], '  ', type(row[1]), type(row))

Tom  -  28    <class 'str'> <class 'list'>
Alice  -  23    <class 'str'> <class 'list'>
Bob  -  34    <class 'str'> <class 'list'>
Sam  -  31    <class 'str'> <class 'list'>


In [24]:
users = [
    {"name": "Tom", "age": 28},
    {"name": "Alice", "age": 23},
    {"name": "Bob", "age": 34}
]
columns = users[0].keys()
list(columns)

['name', 'age']

In [25]:
FILENAME = "files/users2.csv"
 
users = [
    {"name": "Tom", "age": 28},
    {"name": "Alice", "age": 23},
    {"name": "Bob", "age": 34}
]
 
with open(FILENAME, "w", newline="") as file:
    columns = users[0].keys()
    writer = csv.DictWriter(file, fieldnames=columns, delimiter=";")
    writer.writeheader()
     
    # запись нескольких строк
    writer.writerows(users)
     
    user = {"name" : "Sam", "age": 41}
    # запись одной строки
    writer.writerow(user)

In [26]:
with open(FILENAME, "r", newline="") as file:
    reader = csv.reader(file, delimiter=";")
    for row in reader:
        print(row[0], " - ", row[1])

name  -  age
Tom  -  28
Alice  -  23
Bob  -  34
Sam  -  41


In [27]:
with open(FILENAME, "r", newline="") as file:
    reader = csv.DictReader(file, delimiter=";")
    d = list(reader)
d

[OrderedDict([('name', 'Tom'), ('age', '28')]),
 OrderedDict([('name', 'Alice'), ('age', '23')]),
 OrderedDict([('name', 'Bob'), ('age', '34')]),
 OrderedDict([('name', 'Sam'), ('age', '41')])]

In [28]:
d[1]

OrderedDict([('name', 'Alice'), ('age', '23')])

In [29]:
d[1]['age']

'23'

### Формат JSON

Данные в формате JSON (RFC 4627) представляют собой:

- объекты { ... } или
- массивы [ ... ] или
- Значения одного из типов:
- строки в двойных кавычках,
- число,
- логическое значение true/false,
- null.

**JSON (JavaScript Object Notation)** - простой формат обмена данными, основанный на подмножестве синтаксиса JavaScript. Модуль json позволяет кодировать и декодировать данные в удобном формате.

#### Пример

{
```
"firstName": "Иван",  
"lastName": "Иванов",  
"address": {
```
       "streetAddress": "Московское ш., 101, кв.101",
       "city": "Ленинград",
       "postalCode": 101101
   ```
   },
"phoneNumbers": [
   "812 123-1234",
   "916 123-4567"
]
```
}

In [30]:
a = [
    'foo', 
     {
         'bar' : ('baz', None, True, 2, 3.33),
         'bar2': 33
     },
     'foo3'
    ]
a 

['foo', {'bar': ('baz', None, True, 2, 3.33), 'bar2': 33}, 'foo3']

In [31]:
import json

b = json.dumps(a)
b

'["foo", {"bar": ["baz", null, true, 2, 3.33], "bar2": 33}, "foo3"]'

In [33]:
print(json.dumps(a, indent=2))

[
  "foo",
  {
    "bar": [
      "baz",
      null,
      true,
      2,
      3.33
    ],
    "bar2": 33
  },
  "foo3"
]


In [34]:
json.loads(b), a

(['foo', {'bar': ['baz', None, True, 2, 3.33], 'bar2': 33}, 'foo3'],
 ['foo', {'bar': ('baz', None, True, 2, 3.33), 'bar2': 33}, 'foo3'])

# Запомнить!
**Ключи в парах ключ/значение в JSON всегда являются строками. Когда словарь конвертируется в JSON, все ключи словаря преобразовываются в строки. В результате этого, если словарь сначала преобразовать в JSON, а потом обратно в словарь, то можно не получить словарь, идентичный исходному. Другими словами, loads(dumps(x)) != x, если x имеет нестроковые ключи**

### Декодирование

JSON	|  Python
:-------|:----------
object	|dict
array	|list
string	|str
number (int)	|int
number (real)	|float
true	|True
false	|False
null	|None

### Кодирование

Python	| JSON
:------------|:----------
dict	|object
list, tuple	|array
str	|string
int, float	|number
True	|true
False	|false
None	|null

In [35]:
with open("files/JSON_tst.json", 'w') as outfile:
    json.dump(a, outfile, indent=4)

In [36]:
with open("files/JSON_tst.json", 'r') as outfile:
    c = json.load(outfile)
c

['foo', {'bar': ['baz', None, True, 2, 3.33], 'bar2': 33}, 'foo3']

In [37]:
import numpy as np

ar = np.array([1,2,3,4,5,6], dtype=np.float64)

In [38]:
json.dumps(ar)

TypeError: Object of type ndarray is not JSON serializable

In [39]:
ar_s = json.dumps(ar.tolist())
ar_s

'[1.0, 2.0, 3.0, 4.0, 5.0, 6.0]'

In [40]:
ar_new = np.array(json.loads(ar_s))
ar_new

array([1., 2., 3., 4., 5., 6.])

In [41]:
ar = np.array([1,2,3,4,5,6], dtype=np.float64)
ar = ar.reshape(2,3)
ar

array([[1., 2., 3.],
       [4., 5., 6.]])

In [42]:
ar_s = json.dumps(ar.tolist())
ar_s

'[[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]]'

In [43]:
ar_new = np.array(json.loads(ar_s))
ar_new

array([[1., 2., 3.],
       [4., 5., 6.]])

### Бинарные файлы

In [47]:
np.save('files/ar_new.npy', [ar_new, {'k':123}])

In [50]:
ar_new2 = np.load('files/ar_new.npy', allow_pickle=True)
ar_new2

array([array([[1., 2., 3.],
       [4., 5., 6.]]), {'k': 123}], dtype=object)

In [51]:
import pickle

class SomeClass(object):
    def __init__(self):
        self.a = 1
        self.b = [1,2,3,4]
        self.c = {'5': 6, 7: '8'}
        self.d = np.array([[7,8,9],[10,11,12]])
        
        
    def __str__(self):
        return f'a={self.a}, b={self.b}, c={self.c}, d={self.d}'

ob = SomeClass()
print(ob)

a=1, b=[1, 2, 3, 4], c={'5': 6, 7: '8'}, d=[[ 7  8  9]
 [10 11 12]]


In [52]:
with open('files/pickle.bin', 'wb') as f:
    pickle.dump(ob, f)

In [53]:
with open('files/pickle.bin', 'rb') as f:
    ob2 = pickle.load(f)
print(ob2)

a=1, b=[1, 2, 3, 4], c={'5': 6, 7: '8'}, d=[[ 7  8  9]
 [10 11 12]]
